@SUPABASE_URL = http://localhost:54321
@SUPABASE_ANON_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
@SUPABASE_SERVICE_ROLE_KEY = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
# --------------------------------------------------
@protocol = http
@host = localhost
@port = 3000


@API_HOST = {{protocol}}://{{host}}:{{port}}

@TREE_ID = _2100186a5c
@USER_ID = auth0|abc
@USER_NAME = foo

# @API_HOST = https://giessdenkiez-de-postgres-api-git-dev-technologiestiftung1.vercel.app

# These needs a .env in the root of the project
# you get these variables from auth0
@audience = {{$dotenv audience}}
@issuer = {{$dotenv issuer}}
@jwksuri = {{$dotenv jwksuri}}
@client_id = {{$dotenv client_id}}
@client_secret = {{$dotenv client_secret}}
# the token below is obtained from the
# request to the token issuer
# https://YOUR-tenant.eu.auth0.com/oauth/token
# see section POST AUTH
@token = {{$dotenv token}}

  #####  ####### #######
 #     # #          #
 #       #          #
 #  #### #####      #
 #     # #          #
 #     # #          #
  #####  #######    #


### Healthcheck
GET {{API_HOST}}

### GET tree by its id byid ✓

GET {{API_HOST}}/get/byid&id={{TREE_ID}}

### GET a list of all waterd trees ✓

GET {{API_HOST}}/get/watered

### GET list of trees from an list of ids ✓

GET {{API_HOST}}/get/treesbyids&tree_ids={{TREE_ID}},_00096p5ra

### GET a list of trees with the properities ✓
# adopted (how many users)
# waterd how often in the last 30days

GET {{API_HOST}}/get/wateredandadopted

### get all trees with id, lat, lon, radolan_sum ✓
#  with pagination

GET {{API_HOST}}/get/all&limit=4&offset=5


### get all trees

GET {{API_HOST}}/get/all



### GET trees by age

GET {{API_HOST}}/get/byage&start=1800&end=2023

### GET count of trees by age ✓

GET {{API_HOST}}/get/countbyage&start=1800&end=2023



  #####  ####### #######
 #     # #          #
 #       #          #
 #  #### #####      #
 #     # #          #
 #     # #          #
  #####  #######    #

    #
   # #
  #   #
 #     #
 #######
 #     #
 #     #

 ####### ####### #    # ####### #     #
    #    #     # #   #  #       ##    #
    #    #     # #  #   #       # #   #
    #    #     # ###    #####   #  #  #
    #    #     # #  #   #       #   # #
    #    #     # #   #  #       #    ##
    #    ####### #    # ####### #     #


### POST to the token issuer and get an JWT token
# for authenticated requests
POST {{issuer}}oauth/token
Content-Type: application/json

{
    "client_id": "{{client_id}}",
    "client_secret": "{{client_secret}}",
    "audience": "{{audience}}",
    "grant_type": "client_credentials"
}



  #####  ####### #######
 #     # #          #
 #       #          #
 #  #### #####      #
 #     # #          #
 #     # #          #
  #####  #######    #

   #    #     # ####### #     #
  # #   #     #    #    #     #
 #   #  #     #    #    #     #
#     # #     #    #    #######
####### #     #    #    #     #
#     # #     #    #    #     #
#     #  #####     #    #     #

### GET trees that where watered by aq specific user ✓

GET {{API_HOST}}/get/wateredbyuser&uuid={{USER_ID}}
Authorization: Bearer {{token}}

### GET check if a tree is adopted by a specific user ✓

{{API_HOST}}/get/istreeadopted&uuid={{USER_ID}}&id={{TREE_ID}}
Authorization: Bearer {{token}}


### GET trees that are adopted by a specific user ✓

{{API_HOST}}/get/adopted&uuid={{USER_ID}}
Authorization: Bearer {{token}}


### GET the last watering of a specific tree with all the users ✓

{{API_HOST}}/get/lastwatered&id={{TREE_ID}}

 ######  #######  #####  #######
 #     # #     # #     #    #
 #     # #     # #          #
 ######  #     #  #####     #
 #       #     #       #    #
 #       #     # #     #    #
 #       #######  #####     #

    #    #     # ####### #     #
   # #   #     #    #    #     #
  #   #  #     #    #    #     #
 #     # #     #    #    #######
 ####### #     #    #    #     #
 #     # #     #    #    #     #
 #     #  #####     #    #     #


### POST water a tree

POST {{API_HOST}}/post/water
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "timestamp":"{{$datetime "YYYY-MM-DD HH:mm:ss"}}",
    "tree_id":"{{TREE_ID}}",
    "uuid": "{{USER_ID}}",
    "username":"{{USER_NAME}}",
    "amount": 100
}

### Adopt a tree

POST {{API_HOST}}/post/adopt
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tree_id":"{{TREE_ID}}",
    "uuid": "{{USER_ID}}"
}

 ######  ####### #       ####### ####### #######
 #     # #       #       #          #    #
 #     # #       #       #          #    #
 #     # #####   #       #####      #    #####
 #     # #       #       #          #    #
 #     # #       #       #          #    #
 ######  ####### ####### #######    #    #######
    #    #     # ####### #     #
   # #   #     #    #    #     #
  #   #  #     #    #    #     #
 #     # #     #    #    #######
 ####### #     #    #    #     #
 #     # #     #    #    #     #
 #     #  #####     #    #     #


### DELETE a tree adoption

DELETE {{API_HOST}}/delete/unadopt
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tree_id":"{{TREE_ID}}",
    "uuid": "{{USER_ID}}"
}

### DELETE a tree watering

DELETE {{API_HOST}}/delete/unwater
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "tree_id":"{{TREE_ID}}",
    "uuid": "{{USER_ID}}"
    "watering_id": 1
}



# ██████  ██    ██ ██████  ███████
# ██   ██ ██    ██ ██   ██ ██
# ██████  ██    ██ ██████  █████
# ██      ██    ██ ██   ██ ██
# ██       ██████  ██   ██ ███████

# ███████ ██    ██ ██████   █████  ██████   █████  ███████ ███████
# ██      ██    ██ ██   ██ ██   ██ ██   ██ ██   ██ ██      ██
# ███████ ██    ██ ██████  ███████ ██████  ███████ ███████ █████
#      ██ ██    ██ ██      ██   ██ ██   ██ ██   ██      ██ ██
# ███████  ██████  ██      ██   ██ ██████  ██   ██ ███████ ███████


#  █████  ██████  ██
# ██   ██ ██   ██ ██
# ███████ ██████  ██
# ██   ██ ██      ██
# ██   ██ ██      ██


### SUPABASE REST API (anon) (swagger)

GET {{SUPABASE_URL}}/rest/v1/
apikey: {{SUPABASE_ANON_KEY}}


### HEAD to trees_watered (anon)
# Use this to get the right amount of items returned

HEAD {{SUPABASE_URL}}/rest/v1/trees_watered
apikey: {{SUPABASE_ANON_KEY}}
Authorization: Bearer {{SUPABASE_SERVICE_ROLE_KEY}}
Range-Unit: items
Range: 33-300
Prefer: count=exact


### GET trees_watered (sudo mode since RLS is in effect)

GET {{SUPABASE_URL}}/rest/v1/trees_watered
apikey: {{SUPABASE_ANON_KEY}}
Authorization: Bearer {{SUPABASE_SERVICE_ROLE_KEY}}


### RPC get_watered_and_adopted
GET {{SUPABASE_URL}}/rest/v1/rpc/get_watered_and_adopted
apikey: {{SUPABASE_ANON_KEY}}
Range-Unit: items
Prefer: count=exact

