name: Deploy Migrations to Staging

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  deploy:
    environment: staging
    runs-on: ubuntu-22.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      STAGING_PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.106.1

      - run: |
          supabase link --project-ref $STAGING_PROJECT_ID
          supabase db push
