name: Deploy Migrations to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-24.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      PRODUCTION_PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: 2.20.3

      - run: |
          supabase link --project-ref $PRODUCTION_PROJECT_ID
          supabase db push
          supabase functions deploy
